In [1]:
import kagglehub
import os
import pandas as pd
import glob
import warnings
warnings.filterwarnings('ignore')

c:\Users\Jeremmy\LocalProjects\Python_Things\.venv312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DatasetPath = kagglehub.dataset_download("geraldooizx/g-coffee-shop-transaction-202307-to-202506")

In [3]:
def load_multiple_csvs(pattern):
    files = glob.glob(pattern)
    return pd.concat((pd.read_csv(f) for f in files), ignore_index=True)

df_Trans = load_multiple_csvs(os.path.join(DatasetPath, "transactions", "*.csv"))
df_TransItem = load_multiple_csvs(os.path.join(DatasetPath, "transaction_items", "*.csv"))
df_Users = load_multiple_csvs(os.path.join(DatasetPath, "users", "*.csv"))

df_menu = pd.read_csv(os.path.join(DatasetPath, "menu_items", "menu_items.csv"))
df_stores = pd.read_csv(os.path.join(DatasetPath, "stores", "stores.csv"))
df_vouchers = pd.read_csv(os.path.join(DatasetPath, "vouchers", "vouchers.csv"))
df_payments = pd.read_csv(os.path.join(DatasetPath, "payment_methods", "payment_methods.csv"))

In [4]:
df_Trans

,transaction_id,store_id,payment_method_id,voucher_id,user_id,original_amount,discount_applied,final_amount,created_at
0,2ae6d188-76c2-4095-b861-ab97d3cd9312,4,5,NaN,NaN,38.0,0.0,38.0,2023-07-01 07:00:00
1,7d0a474d-62f4-442a-96b6-a5df2bda8832,7,1,NaN,NaN,33.0,0.0,33.0,2023-07-01 07:00:02
2,85f86fef-fddb-4eef-9dc3-1444553e6108,1,5,NaN,NaN,27.0,0.0,27.0,2023-07-01 07:00:04
3,4c41d179-f809-4d5a-a5d7-acb25ae1fe98,5,2,NaN,NaN,45.5,0.0,45.5,2023-07-01 07:00:21
4,51e44c8e-4812-4a15-a9f9-9a46b62424d6,8,5,NaN,NaN,27.0,0.0,27.0,2023-07-01 07:00:33
...,...,...,...,...,...,...,...,...,...
14623686,ac96bb0f-fd77-494e-8752-0eeb914bc5f6,1,2,NaN,1710441.0,69.0,0.0,69.0,2025-06-01 14:18:43
14623687,4f4f8a0d-93dd-4374-99c9-0bc7f1221076,8,1,NaN,97151.0,14.0,0.0,14.0,2025-06-01 14:18:44
14623688,69b46738-f158-409b-be08-5d5cd91b0ce3,3,4,NaN,215599.0,27.0,0.0,27.0,2025-06-01 14:18:45
14623689,29dcf7e6-6b53-4823-a7e5-30da9199c537,8,1,NaN,1398327.0,17.0,0.0,17.0,2025-06-01 14:18:46
14623690,b5f0615b-ec8c-4cea-a0b9-406521546b2f,5,1,NaN,1697271.0,44.5,0.0,44.5,2025-06-01 14:18:51

In [5]:
df_Trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14623691 entries, 0 to 14623690
Data columns (total 9 columns):
 #   Column             Dtype
---  ------             -----
 0   transaction_id     object
 1   store_id           int64
 2   payment_method_id  int64
 3   voucher_id         float64
 4   user_id            float64
 5   original_amount    float64
 6   discount_applied   float64
 7   final_amount       float64
 8   created_at         object
dtypes: float64(5), int64(2), object(2)
memory usage: 1004.1+ MB

In [6]:
df_TransItem

,transaction_id,item_id,quantity,unit_price,subtotal,created_at
0,2ae6d188-76c2-4095-b861-ab97d3cd9312,6,3,9.5,28.5,2023-07-01 07:00:00
1,2ae6d188-76c2-4095-b861-ab97d3cd9312,6,1,9.5,9.5,2023-07-01 07:00:00
2,7d0a474d-62f4-442a-96b6-a5df2bda8832,5,3,9.0,27.0,2023-07-01 07:00:02
3,7d0a474d-62f4-442a-96b6-a5df2bda8832,1,1,6.0,6.0,2023-07-01 07:00:02
4,85f86fef-fddb-4eef-9dc3-1444553e6108,7,3,9.0,27.0,2023-07-01 07:00:04
...,...,...,...,...,...,...
29246318,060c470d-cca6-447f-a2e0-54701f023553,2,1,7.0,7.0,2025-06-01 14:07:50
29246319,31b3c51f-00b3-4ec8-bf53-498542d9d8d1,2,2,7.0,14.0,2025-06-01 14:07:51
29246320,31b3c51f-00b3-4ec8-bf53-498542d9d8d1,8,3,10.0,30.0,2025-06-01 14:07:51
29246321,c38c4831-78e4-4152-b288-648893f47e97,4,3,8.0,24.0,2025-06-01 14:07:55
29246322,c38c4831-78e4-4152-b288-648893f47e97,8,2,10.0,20.0,2025-06-01 14:07:55

In [7]:
df_TransItem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29246323 entries, 0 to 29246322
Data columns (total 6 columns):
 #   Column          Dtype
---  ------          -----
 0   transaction_id  object
 1   item_id         int64
 2   quantity        int64
 3   unit_price      float64
 4   subtotal        float64
 5   created_at      object
dtypes: float64(2), int64(2), object(2)
memory usage: 1.3+ GB

In [8]:
df_Users

         user_id  gender   birthdate        registered_at
0              1  female  1970-04-22  2023-07-01 08:13:07
1              2  female  1991-12-08  2023-07-01 09:53:48
2              3  female  1971-03-15  2023-07-01 10:07:00
3              4    male  1975-11-08  2023-07-01 10:28:08
4              5    male  2005-05-10  2023-07-01 11:02:21
...          ...     ...         ...                  ...
2196252  2018388    male  1970-10-23  2025-06-01 09:56:31
2196253  2018389    male  1983-12-31  2025-06-01 09:56:34
2196254  2018390  female  1991-12-21  2025-06-01 09:56:44
2196255  2018391  female  1978-04-25  2025-06-01 09:56:47
2196256  2018392    male  1992-12-27  2025-06-01 09:56:51

[2196257 rows x 4 columns]

In [9]:
df_Users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196257 entries, 0 to 2196256
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   user_id        int64
 1   gender         object
 2   birthdate      object
 3   registered_at  object
dtypes: int64(1), object(3)
memory usage: 67.0+ MB

In [10]:
df_stores

,store_id,store_name,street,postal_code,city,state,latitude,longitude
0,1,G Coffee @ USJ 89q,Jalan Dewan Bahasa 5/9,50998,USJ 89q,Kuala Lumpur,3.117134,101.615027
1,2,G Coffee @ Kondominium Putra,Jln Yew 6X,63826,Kondominium Putra,Selangor Darul Ehsan,2.959571,101.517720
2,3,G Coffee @ USJ 57W,Jalan Bukit Petaling 5/16C,62094,USJ 57W,Putrajaya,2.951038,101.663698
3,4,G Coffee @ Kampung Changkat,Jln 6/6A,62941,Kampung Changkat,Putrajaya,2.914594,101.704486
4,5,G Coffee @ Seksyen 21,Jalan Anson 4k,62595,Seksyen 21,Putrajaya,2.937599,101.698478
5,6,G Coffee @ Alam Tun Hussein Onn,Jln Pasar Besar 63s,63518,Alam Tun Hussein Onn,Selangor Darul Ehsan,3.279175,101.784923
6,7,G Coffee @ Damansara Saujana,Jln 8/74,65438,Damansara Saujana,Selangor Darul Ehsan,3.220810,101.584590
7,8,G Coffee @ Bandar Seri Mulia,Jalan Wisma Putra,58621,Bandar Seri Mulia,Kuala Lumpur,3.140674,101.706562
8,9,G Coffee @ PJS8,Jalan 7/3o,62418,PJS8,Putrajaya,2.952444,101.702623
9,10,G Coffee @ Taman Damansara,Jln 2,67102,Taman Damansara,Selangor Darul Ehsan,3.497178,101.595271

In [11]:
df_stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   store_id     10 non-null     int64
 1   store_name   10 non-null     object
 2   street       10 non-null     object
 3   postal_code  10 non-null     int64
 4   city         10 non-null     object
 5   state        10 non-null     object
 6   latitude     10 non-null     float64
 7   longitude    10 non-null     float64
dtypes: float64(2), int64(2), object(4)
memory usage: 772.0+ bytes

In [12]:
df_menu

,item_id,item_name,category,price,is_seasonal,available_from,available_to
0,1,Espresso,coffee,6.0,False,NaN,NaN
1,2,Americano,coffee,7.0,False,NaN,NaN
2,3,Latte,coffee,8.0,False,NaN,NaN
3,4,Cappuccino,coffee,8.0,False,NaN,NaN
4,5,Flat White,coffee,9.0,False,NaN,NaN
5,6,Mocha,coffee,9.5,False,NaN,NaN
6,7,Hot Chocolate,non-coffee,9.0,False,NaN,NaN
7,8,Matcha Latte,non-coffee,10.0,False,NaN,NaN

In [13]:
df_menu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   item_id         8 non-null      int64
 1   item_name       8 non-null      object
 2   category        8 non-null      object
 3   price           8 non-null      float64
 4   is_seasonal     8 non-null      bool
 5   available_from  0 non-null      float64
 6   available_to    0 non-null      float64
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 524.0+ bytes

In [14]:
df_vouchers

,voucher_id,voucher_code,discount_type,discount_value,valid_from,valid_to
0,1,SALES77,percentage,7.0,2023-07-07,2023-07-09
1,2,SALES88,percentage,8.0,2023-08-08,2023-08-10
2,3,SALES99,percentage,9.0,2023-09-09,2023-09-11
3,4,SALES10,percentage,10.0,2023-10-10,2023-10-12
4,5,SALES11,percentage,11.0,2023-11-11,2023-11-13
5,6,MERDEKA,fixed,5.0,2023-08-31,2023-09-02
6,7,SALES66,percentage,6.0,2024-06-06,2024-06-08
7,8,SALES77,percentage,7.0,2024-07-07,2024-07-09
8,9,SALES88,percentage,8.0,2024-08-08,2024-08-10
9,10,SALES99,percentage,9.0,2024-09-09,2024-09-11
10,11,SALES10,percentage,10.0,2024-10-10,2024-10-12
11,12,SALES11,percentage,11.0,2024-11-11,2024-11-13
12,13,MERDEKA,fixed,5.0,2024-08-31,2024-09-02
13,14,SALES50,percentage,50.0,2024-05-01,2024-05-01
14,15,SALES66,percentage,6.0,2025-06-06,2025-06-08
15,16,SALES50,percentage,50.0,2025-05-01,2025-05-01

In [15]:
df_vouchers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   voucher_id      16 non-null     int64
 1   voucher_code    16 non-null     object
 2   discount_type   16 non-null     object
 3   discount_value  16 non-null     float64
 4   valid_from      16 non-null     object
 5   valid_to        16 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 900.0+ bytes

In [16]:
df_payments

   method_id  method_name category
0          1         cash     cash
1          2  credit_card     card
2          3   debit_card     card
3          4          tng  ewallet
4          5      grabpay  ewallet

In [17]:
df_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   method_id    5 non-null      int64
 1   method_name  5 non-null      object
 2   category     5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [18]:
before1 = df_Trans.memory_usage(deep=True).sum() / 1024**2
before2 = df_TransItem.memory_usage(deep=True).sum() / 1024**2
before3 = df_Users.memory_usage(deep=True).sum() / 1024**2
before4 = df_stores.memory_usage(deep=True).sum() / 1024**2
before5 = df_menu.memory_usage(deep=True).sum() / 1024**2
print(f"Memory usage before optimization:")
print(f"Transactions: {before1:.2f} MB")
print(f"Transaction Items: {before2:.2f} MB")
print(f"Users: {before3:.2f} MB")
print(f"Stores: {before4:.2f} MB")  
print(f"Menu Items: {before5:.2f} MB")

Memory usage before optimization:
Transactions: 2914.76 MB
Transaction Items: 5159.92 MB
Users: 395.86 MB
Stores: 0.00 MB
Menu Items: 0.00 MB

In [19]:
from function import optimize_numeric_data
from function import optimize_object_data
df_Trans = optimize_numeric_data(df_Trans)
df_Trans = optimize_object_data(df_Trans)
df_TransItem = optimize_numeric_data(df_TransItem)
df_TransItem = optimize_object_data(df_TransItem)
df_Users = optimize_numeric_data(df_Users)
df_Users = optimize_object_data(df_Users)
df_stores = optimize_numeric_data(df_stores)
df_stores = optimize_object_data(df_stores)
df_menu = optimize_numeric_data(df_menu)
df_menu = optimize_object_data(df_menu)
df_vouchers = optimize_numeric_data(df_vouchers)
df_vouchers = optimize_object_data(df_vouchers)
df_payments = optimize_numeric_data(df_payments)
df_payments = optimize_object_data(df_payments)

In [20]:
after1 = df_Trans.memory_usage(deep=True).sum() / 1024**2
after2 = df_TransItem.memory_usage(deep=True).sum() / 1024**2
after3 = df_Users.memory_usage(deep=True).sum() / 1024**2
after4 = df_stores.memory_usage(deep=True).sum() / 1024**2
after5 = df_menu.memory_usage(deep=True).sum() / 1024**2
print(f"Memory usage after optimization:")
print(f"Transactions: {after1:.2f} MB")
print(f"Transaction Items: {after2:.2f} MB")
print(f"Users: {after3:.2f} MB")
print(f"Stores: {after4:.2f} MB")
print(f"Menu Items: {after5:.2f} MB")

Memory usage after optimization:
Transactions: 2440.59 MB
Transaction Items: 4546.31 MB
Users: 158.52 MB
Stores: 0.00 MB
Menu Items: 0.00 MB

In [21]:
df_Trans = df_Trans.astype({'user_id': 'Int32'})
df_Trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14623691 entries, 0 to 14623690
Data columns (total 9 columns):
 #   Column             Dtype
---  ------             -----
 0   transaction_id     object
 1   store_id           int8
 2   payment_method_id  int8
 3   voucher_id         float32
 4   user_id            Int32
 5   original_amount    float32
 6   discount_applied   float32
 7   final_amount       float32
 8   created_at         object
dtypes: Int32(1), float32(4), int8(2), object(2)
memory usage: 543.9+ MB

In [22]:
df_TransItem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29246323 entries, 0 to 29246322
Data columns (total 6 columns):
 #   Column          Dtype
---  ------          -----
 0   transaction_id  object
 1   item_id         int8
 2   quantity        int8
 3   unit_price      float32
 4   subtotal        float32
 5   created_at      object
dtypes: float32(2), int8(2), object(2)
memory usage: 725.2+ MB

In [23]:
df_Users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196257 entries, 0 to 2196256
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   user_id        int32
 1   gender         category
 2   birthdate      category
 3   registered_at  object
dtypes: category(2), int32(1), object(1)
memory usage: 32.0+ MB

In [24]:
df_stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   store_id     10 non-null     int8
 1   store_name   10 non-null     object
 2   street       10 non-null     object
 3   postal_code  10 non-null     int32
 4   city         10 non-null     object
 5   state        10 non-null     object
 6   latitude     10 non-null     float32
 7   longitude    10 non-null     float32
dtypes: float32(2), int32(1), int8(1), object(4)
memory usage: 582.0+ bytes

In [25]:
df_menu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   item_id         8 non-null      int8
 1   item_name       8 non-null      object
 2   category        8 non-null      object
 3   price           8 non-null      float32
 4   is_seasonal     8 non-null      bool
 5   available_from  0 non-null      float32
 6   available_to    0 non-null      float32
dtypes: bool(1), float32(3), int8(1), object(2)
memory usage: 372.0+ bytes

In [26]:
df_Trans.to_parquet( "transactions.parquet")
df_TransItem.to_parquet( "transaction_items.parquet")
df_Users.to_parquet( "users.parquet")
df_stores.to_parquet( "stores.parquet")
df_menu.to_parquet( "menu_items.parquet")
df_payments.to_parquet("paymentsUnique.parquet")
df_vouchers.to_parquet("vouchers.parquet")

In [27]:
import gc
gc.collect()

0